name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  resource_group_name: rg-github-actions
  location: westus2
  subscription_id: 7bbeb4e8-a5e2-43d4-895e-ee47d0f76020

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy Resource Group (with azure cli)
      #   uses: Azure/cli@v1
      #   with:
      #     inlinescript: |
      #       az deployment sub create --location "${{ env.location }}" --template-file ./arm-templates/resource-group.json

      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscription_id }}
          region: ${{ env.location }}
          template: ./arm-templates/resource-group.json
          parameters: location=${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id}}
          template: ./arm-templates/storage-account.json
          parameters: ./arm-templates/storage-account.parameters.json
            storageAccountName=globostg9876
            location=westus3
          deploymentMode: incremental

      # - run: echo ${{ steps.storageAccountDeploy.outputs.blobUri }}
