name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy Resource Group (with azure cli)
      #   uses: Azure/cli@v1
      #   with:
      #     inlinescript: |
      #       az deployment sub create --location "westus2" --template-file ./arm-templates/resource-group.json

      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 7bbeb4e8-a5e2-43d4-895e-ee47d0f76020
          region: westus3
          template: ./arm-templates/resource-group.json
          deploymentName: rg-github-actions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-github-actions
          subscriptionId: 7bbeb4e8-a5e2-43d4-895e-ee47d0f76020
          template: ./arm-templates/storage-account.json
          parameters: 
            ./arm-templates/storage-account.parameters.json
            storageAccountName=globostg9876
            location="westus3"
          deploymentMode: incremental
