name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  subscription_id: 7bbeb4e8-a5e2-43d4-895e-ee47d0f76020

jobs:
  armDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    env:
      resource_group_name: rg-stg-github-actions
      location: westus2

    environment:
      name: staging

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy Resource Group (with azure cli)
      #   uses: Azure/cli@v1
      #   with:
      #     inlinescript: |
      #       az deployment sub create --location "${{ env.location }}" --template-file ./arm-templates/resource-group.json

      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscription_id }}
          region: westus2
          template: ./arm-templates/resource-group.json
          parameters: location=${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id}}
          template: ./arm-templates/storage-account.json
          parameters: ./arm-templates/storage-account.parameters.json
            storageAccountName=globostg9876
            location=${{ env.location }}
          deploymentMode: incremental

      - run: echo ${{ secrets.UBUNTU_ADMIN_PASSWORD }}

  armDeployProduction:
    name: Deploy to Production
    runs-on: ubuntu-latest

    env:
      resource_group_name: rg-prod-github-actions
      location: eastus

    environment:
      name: production

    needs: armDeployStaging

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy Resource Group (with azure cli)
      #   uses: Azure/cli@v1
      #   with:
      #     inlinescript: |
      #       az deployment sub create --location "${{ env.location }}" --template-file ./arm-templates/resource-group.json

      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscription_id }}
          region: westus2
          template: ./arm-templates/resource-group.json
          parameters: location=${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id}}
          template: ./arm-templates/storage-account.json
          parameters: ./arm-templates/storage-account.parameters.json
            storageAccountName=globoprod9876
            location=${{ env.location }}
          deploymentMode: incremental

      - run: echo ${{ secrets.UBUNTU_ADMIN_PASSWORD }}