name: "Bicep Deploy Workflow"

on:
  workflow_dispatch:

env:
  subscription_id: 7bbeb4e8-a5e2-43d4-895e-ee47d0f76020
  azure_region: westus2

jobs:
  bicepDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    env:
      resource_group_name: bicep-rg-staging
      location: westus2

    environment:
      name: staging

    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: deploy resource group
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscription_id }}
          region: ${{ env.azure_region }}
          template: ./bicep-templates/resource-group.bicep
          parameters: location=${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Virtual Network
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id}}
          template: ./bicep-templates/virtual-network.bicep
          parameters: vNetPrefix=bicep-deploy
            location=${{ env.location }}
          deploymentMode: incremental

  bicepDeployProduction:
    name: Deploy to Production
    needs: bicepDeployStaging
    runs-on: ubuntu-latest

    env:
      resource_group_name: bicep-rg-production
      location: westus2

    environment:
      name: production

    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: deploy resource group
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscription_id }}
          region: ${{ env.azure_region }}
          template: ./bicep-templates/resource-group.bicep
          parameters: location=${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Virtual Network
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id}}
          template: ./bicep-templates/virtual-network.bicep
          parameters: vNetPrefix=bicep-deploy
            location=${{ env.location }}
          deploymentMode: incremental
